From SimpleC.EE.concur_triple_critical Require Import triple_critical_strategy_goal triple_critical_strategy_proof.

Module triple_critical_Strategy_Correctness : triple_critical_Strategy_Correct.
  Include triple_critical_strategy_proof.
End triple_critical_Strategy_Correctness.
